services:
    gravitlauncher:
        image: ghcr.io/gravitlauncher/launcher:v5.7.6
        restart: always
        stdin_open: true
        tty: true
        volumes:
        - launcher:/app/data
        environment:
            ADDRESS: "localhost:17549"
            PROJECTNAME: "GravitLauncher"
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        restart: always
        volumes:
            - launcher:/volume
        ports:
            - 17549:80
        depends_on:
            - gravitlauncher
volumes:
    launcher:
